from typing import AsyncIterator, Dict, Protocol, List

class CapLLM(Protocol):
    async def load(self) -> None: ...
    async def reload_from_uri(self, uri: str) -> None: ...
    async def run(self, prompt: str, params: Dict) -> str: ...
    async def stream(self, prompt: str, params: Dict) -> AsyncIterator[str]: ...
    def supported_modes(self) -> List[str]: ...
    async def close(self) -> None: ...
